import java.awt.Font;
import java.awt.font.FontRenderContext;
import java.awt.font.GlyphVector;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Development-only generator for the bundled text metrics tables.
 *
 * <p>Reads TrueType faces and prints {@code family \t weight \t style \t char \t units}
 * rows in font units (unitsPerEm=2048). The numbers are committed; the build and the
 * tests never need the fonts. Run from the repository root:
 *
 * <pre>
 *   java tools/GenMetrics.java "Segoe UI" \
 *       ~/.fonts/segoeUI/segoeui.ttf:400:normal \
 *       ~/.fonts/segoeUI/seguisb.ttf:600:normal \
 *       ~/.fonts/segoeUI/segoeuii.ttf:400:italic \
 *       &gt; src/main/resources/metrics/segoe-ui-metrics.txt
 * </pre>
 */
public final class GenMetrics {

    private static final float PROBE_SIZE = 1000f;
    private static final int UNITS_PER_EM = 2048;

    /** The Unicode ranges emitted; only code points the face can render are kept. */
    private static final int[][] RANGES = {
            {0x0020, 0x007E}, // ASCII printable
            {0x00A0, 0x00FF}, // Latin-1 Supplement
            {0x0100, 0x017F}, // Latin Extended-A
            {0x0401, 0x0401}, // Ё
            {0x0410, 0x044F}, // Cyrillic А-я
            {0x0451, 0x0451}, // ё
            {0x2010, 0x2027}, // General Punctuation
            {0x20AC, 0x20AC}, // €
            {0x221E, 0x221E}, // ∞
    };

    private record Face(String path, String weight, String style) {
    }

    private GenMetrics() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("usage: GenMetrics <family> <ttf:weight:style>...");
            System.exit(2);
        }
        String family = args[0];
        List<Face> faces = new ArrayList<>();
        for (int i = 1; i < args.length; i++) {
            String[] parts = args[i].split(":");
            faces.add(new Face(parts[0], parts[1], parts[2]));
        }
        String header = "# font metrics generated by tools/GenMetrics.java (unitsPerEm="
                + UNITS_PER_EM + "); do not edit by hand\n"
                + "# family\tweight\tstyle\tchar\tunits\n";
        StringBuilder out = new StringBuilder(header);
        for (Face face : faces) {
            Font font = Font.createFont(Font.TRUETYPE_FONT, new File(face.path()))
                    .deriveFont(PROBE_SIZE);
            FontRenderContext context = new FontRenderContext(null, true, true);
            for (int[] range : RANGES) {
                for (int cp = range[0]; cp <= range[1]; cp++) {
                    if (!font.canDisplay(cp)) {
                        continue;
                    }
                    String text = new String(Character.toChars(cp));
                    GlyphVector glyphs = font.createGlyphVector(context, text);
                    float advance = glyphs.getGlyphMetrics(0).getAdvanceX();
                    long units = Math.round(advance * UNITS_PER_EM / PROBE_SIZE);
                    out.append(family).append('\t').append(face.weight()).append('\t')
                            .append(face.style()).append('\t').append(text).append('\t')
                            .append(units).append('\n');
                }
            }
        }
        System.out.write(out.toString().getBytes(StandardCharsets.UTF_8));
        System.out.flush();
    }
}
