package org.jxsd.cli;

import java.util.LinkedHashMap;
import java.util.Map;

import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

/**
 * picocli command for the console mode.
 *
 * <p>Uses standard picocli syntax: short options ({@code -o file},
 * {@code -o=file}) and long options ({@code --output file},
 * {@code --output=file}). The diagram must be written either to a file
 * ({@code -o/--output}) or to stdout ({@code -s/--stdout}); the usage text is
 * generated by picocli from the annotations below.
 */
@Command(
        name = "jxsd",
        header = "XSD diagram generator",
        description = "Renders an XSD component as an SVG or PNG diagram.",
        footer = {
                "Examples:",
                "  jxsd -o out.svg -r Route -e 3 -d input.xsd",
                "  jxsd -o out.png -r tns:Route -N tns=http://example.org/ns input.xsd",
                "  jxsd -s -f png -r '{http://example.org/ns}Route' input.xsd"
        },
        mixinStandardHelpOptions = true,
        sortOptions = false,
        versionProvider = CliOptions.Version.class)
public final class CliOptions {

    @ArgGroup(exclusive = true, multiplicity = "1")
    public Output output;

    public static final class Output {

        @Option(names = {"-o", "--output"}, paramLabel = "FILE",
                description = "output diagram file; the extension selects the format.")
        public String file;

        @Option(names = {"-s", "--stdout"},
                description = "stream the diagram to stdout.")
        public boolean stdout;
    }

    @Option(names = {"-f", "--format"}, paramLabel = "FORMAT",
            description = "output format: 'svg' or 'png' (default inferred from -o, else 'svg').")
    public String format;

    @Option(names = {"-r", "--root"}, required = true, paramLabel = "REF",
            description = "root component: NAME, prefix:NAME or {namespace-uri}NAME.")
    public String root;

    @Option(names = {"-N", "--namespace"}, paramLabel = "PREFIX=URI",
            description = "bind a prefix for -r; repeatable (like xmlns:PREFIX).")
    public Map<String, String> namespaces = new LinkedHashMap<>();

    @Option(names = {"-k", "--kind"}, paramLabel = "KIND",
            description = "root kind: element, complexType, simpleType or group (else inferred).")
    public String kind;

    @Option(names = {"-e", "--expand"}, paramLabel = "N", defaultValue = "1",
            description = "expand level (0 or more).")
    public int expandLevel;

    @Option(names = {"-d", "--documentation"},
            description = "show the documentation.")
    public boolean showDocumentation;

    @Option(names = {"-l", "--language"}, paramLabel = "LANG",
            description = "preferred documentation language (xml:lang).")
    public String language;

    @Option(names = {"--all-languages"},
            description = "concatenate every documentation language instead of selecting one.")
    public boolean allLanguages;

    @Option(names = {"--text-length"},
            description = "pin every text run to its computed width so the layout survives a font substitution.")
    public boolean textLength;

    @Option(names = {"--scale"}, paramLabel = "FACTOR", defaultValue = "1.0",
            description = "scale factor for the PNG raster (default 1.0; requires PNG output).")
    public double scale;

    @Option(names = {"-u", "--username"}, paramLabel = "USERNAME",
            description = "username for secured XSD dependencies (import/include).")
    public String username;

    @Option(names = {"-p", "--password"}, paramLabel = "PASSWORD",
            description = "password for secured XSD dependencies (import/include).")
    public String password;

    @Option(names = {"--password-file"}, paramLabel = "FILE",
            description = "read the dependency password from FILE (alternative to -p).")
    public String passwordFile;

    @Parameters(index = "0", arity = "1", paramLabel = "FILE",
            description = "the XSD file or URL to render.")
    public String inputFile;

    public CliOptions() {}

    /** A command line configured with the options above. */
    public static CommandLine commandLine() {
        return new CommandLine(new CliOptions());
    }

    /** The XSD file or URL to render. */
    public String inputFile() {
        return inputFile;
    }

    public boolean outputOnStdOut() {
        return output.stdout;
    }

    public String outputFile() {
        return output.file;
    }

    /** Prints "jxsd, version &lt;x&gt;" for {@code -V/--version}. */
    public static final class Version implements CommandLine.IVersionProvider {

        @Override
        public String[] getVersion() {
            Package pkg = CliOptions.class.getPackage();
            String version = pkg != null && pkg.getImplementationVersion() != null
                    ? pkg.getImplementationVersion() : "dev";
            return new String[] {"jxsd, version " + version};
        }
    }
}
